name: Generate ASCII Art
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Execute Shell script
              run: |
                chmod +x ascii-script.sh  
                ./ascii-script.sh
            
            - name: Upload ASCII Art
              uses: actions/upload-artifact@v7
              with:
                name: ascii_art
                path: ascii_art.txt
    
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download ASCII Art
              uses: actions/download-artifact@v8
              with:
                name: ascii_art
                path: .
            - name: Sleep for 10 seconds
              run: sleep 10

            - name: Check if file exists
              run: grep -i "dragon" ascii_art.txt || echo "File not found or content missing"
        

    deploy: 
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Download ASCII Art
              uses: actions/download-artifact@v8
              with:
                name: ascii_art
                path: .
            - name: Deploy ASCII Art
              run: |
                echo "Deploying ASCII Art..."
                cat ascii_art.txt